version: '3'

services:
  keycloak:
      image: jboss/keycloak:4.5.0.Final
      environment:
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: password
        DB_VENDOR: MYSQL
        DB_ADDR: mysql
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
      ports:
        - 8080:8080
      depends_on:
        - mysql

  mysql:
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password
      volumes:
        - mysql_data:/var/lib/mysql

volumes:
  mysql_data: