module.exports = {
  SAML_USES_ONLY_ENV_VARS_FOR_SOME_OPTIONS: '',
  SAML_ENABLED: '',
  SAML_ENTRY_POINT: '',
  SAML_ISSUER: '',
  SAML_ATTR_MAPPING_ID: '',
  SAML_ATTR_MAPPING_USERNAME: '',
  SAML_ATTR_MAPPING_MAIL: '',
  SAML_ATTR_MAPPING_FIRST_NAME: '',
  SAML_ATTR_MAPPING_LAST_NAME: '',
  SAML_CERT: ''
}